services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mood_db
    volumes:
      - mood-db:/var/lib/postgresql/data

volumes:
  mood-db: {}